# Generated by Django 5.1 on 2024-08-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_info_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.URLField(blank=True, max_length=233, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='facebook',
            field=models.URLField(blank=True, max_length=233, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='linking',
            field=models.URLField(blank=True, max_length=233, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter',
            field=models.URLField(blank=True, max_length=233, null=True),
        ),
    ]
